### ISSUE TITLE
no module names pyvjoy

### ISSUE THREAD

**Issue by dekid69** [hjstn/miniDjiController#6]
can open vjoy while installed 
= RESTART: C:\Users\beanz\Downloads\miniDjiController-master\miniDjiController-master\main.py
Traceback (most recent call last):
  File "C:\Users\beanz\Downloads\miniDjiController-master\miniDjiController-master\main.py", line 6, in <module>
    import serial, pyvjoy, argparse
ModuleNotFoundError: No module named 'pyvjoy'

**Comment by dekid69** [comment]
still need help

**Comment by hjstn** [comment]
Make sure Pyvjoy is installed for the Python version you are using. The error is unrelated to this project.

https://docs.python.org/3/installing/index.html

**Comment by dekid69** [comment]
> Make sure Pyvjoy is installed for the Python version you are using. The error is unrelated to this project.
> 
> https://docs.python.org/3/installing/index.html

what version does it need to be?

**Comment by hjstn** [comment]
> > Make sure Pyvjoy is installed for the Python version you are using. The error is unrelated to this project.
> > https://docs.python.org/3/installing/index.html
> 
> what version does it need to be?

Any higher than 1.0.1, as listed in the requirements.txt
